# Generated by Django 3.0.1 on 2020-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMarketApp', '0002_auto_20191230_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.CharField(default='info@python.com', max_length=50),
        ),
    ]
