# Generated by Django 3.0.1 on 2020-02-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMarketApp', '0004_auto_20200212_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mail',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Email Addrees'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenumber',
            field=models.IntegerField(blank=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
